#criando o docker
version: '3.8'


services:
    #gerando a imagem do keycloak para utilizar dentro do docker 
    keycloak:
      image: quay.io/keycloak/keycloak:24.0.3
      container_name: keycloak
      command: start-dev
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
        - "8080:8080"
      
