#criando o docker, versão não especificada pois o composer já puxa a melhor versão para o que necessita

services:
    #gerando a imagem do keycloak para utilizar dentro do docker 
    keycloak:
      #definindo as configurações do keycloak
      image: quay.io/keycloak/keycloak:26.0.8
      container_name: keycloak
      command: start-dev
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
        - "8080:8080"
      
